apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: postgres
  labels:
    app: postgres
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
        volumes:
        - name: postgres-pv
          persistentVolumeClaim:
            claimName: postgres-pvc
        imagePullSecrets:
        - name: regcred
        containers:
            - name: db
              image: postgres:11
              ports:
                - containerPort: 5432              
              args:
              - pg_resetwal
              - /var/lib/postgresql/data
              securityContext:
                runAsUser: 999
              envFrom:
                - configMapRef:
                    name: postgres-config
              volumeMounts:
                - mountPath: /var/lib/postgresql/data
                  name: postgres-pv