apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: postgres
  labels:
    app: postgres
data:
  POSTGRES_DB: agapanto
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: 'agapanto_seguridad_2019'
  PGDATA: '/var/lib/postgresql/data/pgdata'
