kind: Service
apiVersion: v1
metadata:
  name: postgres-svc
  namespace: postgres
spec:
  type: NodePort
  selector:
      app: postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
